services:
  database_postgres:
    image: postgres:16-alpine   
    environment:
      POSTGRES_USER: user  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: mydatabase  
    ports:
      - "5432:5432" 
  
  frontend_app:
    build:
      context: ./client   
      dockerfile: Dockerfile  
    ports:
      - "5173:5173"  
    environment:
      VITE_SITE_KEY : 387jhaypn1

  backend_app:
    build:
      context: ./Back   
      dockerfile: Dockerfile  
    ports:
      - "4000:4000" 
    environment:
      SERVER_HOST: 0.0.0.0 
      SERVER_PORT: 4000     
